ALTER TABLE despesa
    ADD CONSTRAINT FK_DESPESA_ON_CATEGORIA FOREIGN KEY (categoria_id) REFERENCES categoria (id);

ALTER TABLE receita
    ADD CONSTRAINT FK_RECEITA_ON_CATEGORIA FOREIGN KEY (categoria_id) REFERENCES categoria (id);